version: '3'
services:
  jupyter:
    build: .
    volumes:
      - type: bind
        source: "./"
        target: "/home/Jupyterlab/notebook"
    user: root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8888:8888"
    tty: true # retain container up
    # privileged: true
    environment:
      TZ: Asia/Tokyo
    command:
      jupyter lab
        --ip=0.0.0.0
        --allow-root
        --no-browser
        --NotebookApp.notebook_dir='/home/Jupyterlab/notebook'
        --NotebookApp.token='1234'
  poetry:
    build: ./pyproject
    volumes:
      - type: bind
        source: "./pyproject/"
        target: "/src/"
    tty: true # retain container up
